# Generated by Django 6.0.7 on 2026-07-20 01:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('model', models.CharField(default='claude-sonnet-4-6', max_length=80)),
                ('confidence', models.FloatField(default=0.0)),
                ('knowledge_refs', models.JSONField(blank=True, default=list)),
                ('requires_escalation', models.BooleanField(default=False, help_text='Money/legal/PR adjacent — never eligible for auto-send.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google Reviews')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('message', 'Message'), ('comment', 'Comment'), ('mention', 'Mention'), ('tag', 'Tag'), ('review', 'Review')], max_length=20)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('parent_ref', models.CharField(blank=True, max_length=200)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('author_handle', models.CharField(max_length=200)),
                ('author_display_name', models.CharField(max_length=200)),
                ('author_external_id', models.CharField(blank=True, max_length=200)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('media', models.JSONField(blank=True, default=list)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('intent', models.CharField(blank=True, max_length=60)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('drafted', 'Drafted'), ('awaiting_approval', 'Awaiting approval'), ('sent', 'Sent'), ('dismissed', 'Dismissed')], default='new', max_length=30)),
                ('is_outbound', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('media', models.JSONField(blank=True, default=list)),
                ('target_channels', models.JSONField(default=list)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('quiet_hours_start', models.TimeField(default='08:00')),
                ('quiet_hours_end', models.TimeField(default='20:00')),
                ('brand_voice', models.TextField(blank=True, help_text='Tone guidance injected into AI draft prompts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='owner', max_length=120)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('edit', 'Edit'), ('reject', 'Reject')], max_length=20)),
                ('final_text', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.draft')),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='core.interaction'),
        ),
        migrations.CreateModel(
            name='PostPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google Reviews')], max_length=20)),
                ('external_post_id', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('impressions', models.IntegerField(default=0)),
                ('engagements', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('grace', 'Grace period'), ('read_only', 'Read only'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('amount_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('monnify_customer_ref', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('card_token', models.CharField(blank=True, max_length=255)),
                ('reserved_account_number', models.CharField(blank=True, max_length=20)),
                ('reserved_account_bank', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=120, unique=True)),
                ('monnify_transaction_reference', models.CharField(blank=True, max_length=120)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale')], max_length=20)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google Reviews')], max_length=20)),
                ('external_post_id', models.CharField(blank=True, max_length=200)),
                ('metric_name', models.CharField(max_length=60)),
                ('value', models.FloatField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google Reviews')], max_length=20)),
                ('external_account_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('handle', models.CharField(blank=True, max_length=200)),
                ('oauth_tokens', models.JSONField(blank=True, default=dict)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='connected', max_length=30)),
                ('is_mock', models.BooleanField(default=False, help_text='Demo mode — served by MockAdapter behind the real interface.')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google Reviews')], max_length=20)),
                ('unanswered_count', models.IntegerField(default=0)),
                ('oldest_unanswered_seconds', models.IntegerField(default=0)),
                ('median_first_response_seconds', models.IntegerField(blank=True, null=True)),
                ('answered_within_5min_pct', models.FloatField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['tenant', 'status'], name='core_intera_tenant__7a1230_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['tenant', 'channel', 'kind'], name='core_intera_tenant__111feb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('channel', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='channelconnection',
            unique_together={('tenant', 'channel', 'external_account_id')},
        ),
    ]
