# Generated by Django 5.2.16 on 2026-07-21 02:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Client-generated idempotency key (UUID), stable across retries.",
                        max_length=64,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X"),
                            ("google", "Google Reviews"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("recipient_handle", models.CharField(blank=True, max_length=200)),
                (
                    "recipient_display_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("body", models.TextField()),
                ("used_ai_draft", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The outbound Interaction row created in the thread on send.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.interaction",
                    ),
                ),
                (
                    "parent_interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_replies",
                        to="core.interaction",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "next_attempt_at"],
                        name="core_outbou_tenant__b520e8_idx",
                    ),
                    models.Index(
                        fields=["tenant", "thread_id"],
                        name="core_outbou_tenant__79b16f_idx",
                    ),
                ],
                "unique_together": {("tenant", "client_id")},
            },
        ),
    ]
